### ISSUE TITLE
Mob heads

### ISSUE THREAD

**Issue by jstallent** [bjendrick/whocraft_management#4]
We have talked about possibly adding mob head drops to the server. The easiest way to do this would be to add the More Mob Heads system from Xisuma:
https://xisumavoid.com/moremobheads/

**Comment by bjendrick** [comment]
Thank you for jumping into the issues with me... I figured this would help keep things organized since it's been a bit crazy for a while.

**Comment by jstallent** [comment]
Yeah, this is a great place to organize these things.

**Comment by bjendrick** [comment]
My plan is that once we agree on implementing something, I'll create it as a project (with or without a milestone), and that way we can track where it's at... also add any new issues for it, etc.

**Comment by bjendrick** [comment]
This has been completed by @JSunnyDaze using loot tables.
